# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sms', 'SMS'), ('data', 'data')], max_length=25)),
                ('unlimited', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minutes', models.IntegerField(default=0)),
                ('data', models.IntegerField(default=0)),
                ('sms', models.IntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
